spring.application.name=kafka-demo

# Kafka Broker
spring.kafka.bootstrap-servers=localhost:9092

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=postgres
spring.datasource.password=root

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Consumer Group
spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.auto-offset-reset=earliest

#Mail-config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=naveendevarinti5005@gmail.com
spring.mail.password=kmbrspiummwnfyye

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#Redis
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

# Key Deserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Value Deserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Trust Packages
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true